"""Static read-only Runtime OS command registry."""


RUNTIME_COMMAND_REGISTRY = [
    {
        "command_key": "COMMAND_OPEN_HOME",
        "title": "打开管理首页",
        "category": "navigation",
        "risk_level": "low",
        "human_required": False,
        "description": "查看 AI Dashboard 管理首页总览。",
        "recommended_route": "/ai-dashboard/home",
    },
    {
        "command_key": "COMMAND_OPEN_WORKSPACE",
        "title": "打开工作台",
        "category": "navigation",
        "risk_level": "low",
        "human_required": False,
        "description": "查看 AI Dashboard 工作台中心。",
        "recommended_route": "/ai-dashboard/workspace",
    },
    {
        "command_key": "COMMAND_OPEN_MISSION_CONTROL",
        "title": "打开任务指挥中心",
        "category": "navigation",
        "risk_level": "medium",
        "human_required": False,
        "description": "查看 Runtime 任务、阻塞和推荐顺序。",
        "recommended_route": "/ai-dashboard/mission-control",
    },
    {
        "command_key": "COMMAND_OPEN_PRACTICAL_CONSOLE",
        "title": "打开实用控制台",
        "category": "navigation",
        "risk_level": "medium",
        "human_required": False,
        "description": "查看今日必须处理、观察、禁止自动化和本周重点。",
        "recommended_route": "/ai-dashboard#ai-runtime-practical-console",
    },
    {
        "command_key": "COMMAND_OPEN_MODULE_SEARCH",
        "title": "打开模块搜索",
        "category": "navigation",
        "risk_level": "low",
        "human_required": False,
        "description": "搜索 Dashboard 模块与入口。",
        "recommended_route": "/ai-dashboard/module-search",
    },
    {
        "command_key": "COMMAND_OPEN_OPS_HEALTH",
        "title": "打开运维健康中心",
        "category": "ops",
        "risk_level": "medium",
        "human_required": False,
        "description": "查看运维健康、冒烟测试、JSON、路由和导出状态。",
        "recommended_route": "/ai-dashboard/ops-health",
    },
    {
        "command_key": "COMMAND_OPEN_RELEASE_READINESS",
        "title": "打开上线准备度中心",
        "category": "release",
        "risk_level": "high",
        "human_required": True,
        "description": "查看上线准备度和阻塞原因，仅人工复核。",
        "recommended_route": "/ai-dashboard/release-readiness",
    },
    {
        "command_key": "COMMAND_OPEN_EXPORT_OPERATIONS",
        "title": "打开导出运营中心",
        "category": "export",
        "risk_level": "medium",
        "human_required": False,
        "description": "查看导出运营、历史和导出健康状态。",
        "recommended_route": "/ai-dashboard/export-operations",
    },
    {
        "command_key": "COMMAND_OPEN_DOCUMENTATION",
        "title": "打开文档中心",
        "category": "documentation",
        "risk_level": "low",
        "human_required": False,
        "description": "查看 Dashboard 文档、服务、测试和只读矩阵。",
        "recommended_route": "/ai-dashboard/documentation",
    },
    {
        "command_key": "COMMAND_OPEN_NAVIGATION",
        "title": "打开导航中心",
        "category": "documentation",
        "risk_level": "low",
        "human_required": False,
        "description": "查看分类导航、页面入口和快速跳转。",
        "recommended_route": "/ai-dashboard/navigation",
    },
    {
        "command_key": "COMMAND_OPEN_RUNTIME_ARCHIVE",
        "title": "打开高级 Runtime 分析归档区",
        "category": "runtime",
        "risk_level": "medium",
        "human_required": False,
        "description": "查看 Event、Signal、Correlation、Causal、Strategy 等深层分析。",
        "recommended_route": "/ai-dashboard#advanced-runtime-analysis-archive",
    },
    {
        "command_key": "COMMAND_EXPORT_RUNTIME_REPORTS",
        "title": "查看 Runtime 报告导出入口",
        "category": "export",
        "risk_level": "medium",
        "human_required": True,
        "description": "查看 Runtime 报告导出入口，仅展示导出命令语义。",
        "recommended_route": "/ai-dashboard/export-operations",
    },
    {
        "command_key": "COMMAND_RUN_SMOKE_TEST_CHECKLIST",
        "title": "查看冒烟测试清单",
        "category": "ops",
        "risk_level": "medium",
        "human_required": True,
        "description": "查看冒烟测试清单；命令层仅建议，不触发测试执行。",
        "recommended_route": "/ai-dashboard/smoke-test",
    },
    {
        "command_key": "COMMAND_VIEW_RELEASE_RUNBOOK",
        "title": "查看发布 Runbook",
        "category": "release",
        "risk_level": "high",
        "human_required": True,
        "description": "查看发布 Runbook，所有发布动作必须人工处理。",
        "recommended_route": "/ai-dashboard/release-runbook",
    },
    {
        "command_key": "COMMAND_VIEW_RELEASE_PACKAGE",
        "title": "查看发布包",
        "category": "release",
        "risk_level": "high",
        "human_required": True,
        "description": "查看发布包摘要，不触发上线或部署。",
        "recommended_route": "/ai-dashboard/release-package",
    },
    {
        "command_key": "COMMAND_VIEW_RUNTIME_STRATEGY",
        "title": "查看 Runtime 战略",
        "category": "runtime",
        "risk_level": "medium",
        "human_required": False,
        "description": "查看 Runtime Strategy 深层分析归档。",
        "recommended_route": "/ai-dashboard#advanced-runtime-analysis-archive",
    },
    {
        "command_key": "COMMAND_VIEW_RUNTIME_MEMORY",
        "title": "查看 Runtime 记忆",
        "category": "runtime",
        "risk_level": "medium",
        "human_required": False,
        "description": "查看 Runtime Memory 深层分析归档。",
        "recommended_route": "/ai-dashboard#advanced-runtime-analysis-archive",
    },
    {
        "command_key": "COMMAND_REVIEW_HIGH_RISK_AUTOMATION",
        "title": "人工复核高风险自动化",
        "category": "governance",
        "risk_level": "critical",
        "human_required": True,
        "description": "人工复核危险自动化、禁止自动化和自动化边界。",
        "recommended_route": "/ai-dashboard/mission-control",
    },
    {
        "command_key": "COMMAND_REVIEW_GOVERNANCE_CONFLICT",
        "title": "人工复核治理冲突",
        "category": "governance",
        "risk_level": "critical",
        "human_required": True,
        "description": "人工复核治理冲突、宪法冲突和边界冲突。",
        "recommended_route": "/ai-dashboard/mission-control",
    },
    {
        "command_key": "COMMAND_REVIEW_IMMUNE_ALERT",
        "title": "人工复核免疫告警",
        "category": "governance",
        "risk_level": "critical",
        "human_required": True,
        "description": "人工复核系统性风险、免疫告警和高风险突变。",
        "recommended_route": "/ai-dashboard#advanced-runtime-analysis-archive",
    },
    {
        "command_key": "COMMAND_REVIEW_INTEGRITY_RISK",
        "title": "人工复核完整性风险",
        "category": "governance",
        "risk_level": "critical",
        "human_required": True,
        "description": "人工复核完整性冲突、价值分裂和认知不一致。",
        "recommended_route": "/ai-dashboard#advanced-runtime-analysis-archive",
    },
]


def get_runtime_command_registry() -> list[dict]:
    """Return a copy of the static command registry."""
    return [dict(command) for command in RUNTIME_COMMAND_REGISTRY]
